### ISSUE TITLE
Maps is crashing the App

### ISSUE THREAD

**Issue by adappter** [mapsplugin/v2.0-demo#40]
What I'm doing: 
I add some markers on startup. 
After a certain time I clear the map and add again some markers. This happens every certain time, let say e.g. every 2 mins.
The exception throws about the third time I'm adding the markers.

This is the Exception.
```
 FATAL EXCEPTION: main
                                                              Process: com.poko.app, PID: 10038
                                                              java.lang.IllegalStateException: Can't parcel a recycled bitmap
                                                                  at android.graphics.Bitmap.checkRecycled(Bitmap.java:392)
                                                                  at android.graphics.Bitmap.writeToParcel(Bitmap.java:1999)
                                                                  at com.google.android.gms.maps.model.internal.zza$zza$zza.zze(Unknown Source)
                                                                  at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(Unknown Source)
                                                                  at plugin.google.maps.PluginMarker$14.onPostExecute(PluginMarker.java:1008)
                                                                  at plugin.google.maps.PluginMarker$14.onPostExecute(PluginMarker.java:905)
                                                                  at android.os.AsyncTask.finish(AsyncTask.java:660)
                                                                  at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by wf9a5m75** [comment]
Thank you for reporting the certain log.
I checked at [PluginMarker.java:1008](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/b2a51f5c1592e89a5bdebc1c3569fcea5d7e856c/src/android/plugin/google/maps/PluginMarker.java#L1008), but the variable `image` should not be recycled at this time, because the image is just obtained at the `doInBackground()` process.

It means I feel strange for this error log.

So I guess your code has some kind of hints.

Could you show me the code `map.clear() -> addMarker()` part, including all options (url also)?

**Comment by adappter** [comment]
Here you go :)
```
this.map.clear();
      let array = new plugin.google.maps.BaseArrayClass(this.locationTracker.nearestReports);
      array.map( report => {
        let markerOptions: MarkerOptions = {
          'position': new plugin.google.maps.LatLng(report.lat, report.lng),
          'data': report,
          'icon': {
            'url': report.pinImage,
            'anchor': [16, 20],
            'size': {
              width: 32,
              height: 41
            }
          }
        };
        this.map.addMarker(markerOptions).then( (marker: Marker) => {
          marker.addEventListener(GoogleMapsEvent.MARKER_CLICK).subscribe(() =>
          {
            console.log('Marker clicked...');
          }, error => {
            console.log(error);
          });
        }).catch( error => {
          console.log("Marker Add Error: " + error);
        });
      });
    }
```

**Comment by wf9a5m75** [comment]
I wonder why you use the ionic wrapper plugin for v1 to v2.

Anyway, here is my guess:

- if the above code executes repeatedly at the event, such as CAMERA_MOVE_END event, then the reason is `map.clear()` during `array.map()`.

- or the crash occurs when you remove the map div(such as changing the page) during the `array.map()`

----

Currently, the information is very less for me.
Please find out the condition that reproduce the crash 100%.

**Comment by wf9a5m75** [comment]
And usage of `array.map` is incorrect in your code.

`array.map(fn)` uses for receiving the results of execution `fn`.

Basic usage is:

```js

var array = [ 0, ... N ];  //pure JS and

//var array = new plugin.google.maps.BaseArrayClass([ 0, ... N ]);  // this plugin wrapper work this way.

var results = array.map(function(item) {
  return item + 100;
});
```

---

If you use the `map` of `BaseArrayClass`, you can also this:

```js
var array = new plugin.google.maps.BaseArrayClass([ 0, ... N ]);
array.map(function(item, callback) {
  callback(item + 100);
}, function( results ) {
  
});
```

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/map/README.md

**Comment by wf9a5m75** [comment]
So in order to monitoring your code, please modify you code like this:

```js

console.log("---->map.clear");
this.map.clear();

var array = new plugin.google.maps.BaseArrayClass(this.locationTracker.nearestReports);

array.map(function(report, callback) {
   ...
   this.map.addMarker(markerOptions, function(marker) {
      callback(marker);
   });

}, function(markers) {
  console.log("---> Markers are added.");
});

```

**Comment by wf9a5m75** [comment]
I updated the `pluginMarker.java`. That should be prevent crashing for your case.
Please reinstall the plugin.

**Comment by adappter** [comment]
the crash seems to be fixed!
