### ISSUE TITLE
App crashes with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by adappter** [mapsplugin/v2.0-demo#44]
Hey there,

currently my app is crashing when it starts. I don't know if it's because of the update of my Android Phone (Android 7.0). It happens only on Android.

```

06-14 13:47:04.643 5107-5107/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.poko.app, PID: 5107
                                                 java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzac; or its super classes (declaration of 'com.google.android.gms.common.internal.zzac' appears in /data/app/com.poko.app-2/base.apk)
                                                     at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
                                                     at plugin.google.maps.CordovaGoogleMaps$1.run(CordovaGoogleMaps.java:228)
                                                     at android.app.Activity.runOnUiThread(Activity.java:6030)
                                                     at plugin.google.maps.CordovaGoogleMaps.initialize(CordovaGoogleMaps.java:94)
                                                     at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
                                                     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
                                                     at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
                                                     at org.apache.cordova.PluginManager.init(PluginManager.java:86)
                                                     at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:115)
                                                     at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
                                                     at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
                                                     at com.poko.app.MainActivity.onCreate(MainActivity.java:39)
                                                     at android.app.Activity.performCreate(Activity.java:6912)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by wf9a5m75** [comment]
It seems your project does not include the Google play services when it is compiled.

How did you build your app?

**Comment by adappter** [comment]
cordova run android

The SDK Manager says that Google Play Services is installed.

**Comment by wf9a5m75** [comment]
It means the SDK manager installed the Google Play Services to your pc

**Comment by adappter** [comment]
So, how can I check it?

**Comment by wf9a5m75** [comment]
The other case of the issue is your Android does not have the google play framework.

Does your Android have the Google Play Store?

If yes, you need to install this library.
https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en

If no, you can not use the Google Maps Android API v2 (it means you can not use this plugin)

If your Android has the Google play framework(google play store) and the Google Play services is installed, then please share your project files on github or bitbucket.
I will check your project.

How and why? Read here.
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1479

**Comment by adappter** [comment]
Google Play Services is installed on my device.
As I told it works before the software update.

I sent you an invitation.

**Comment by adappter** [comment]
Did you already took a look?

**Comment by wf9a5m75** [comment]
I have no problem with the latest version of the plugin and the Google play services.
Unfortunately I have been so busy. I haven't checked your repo yet.

**Comment by adappter** [comment]
I testes on a Samsung Galaxy S7 end Samsung Galaxy S6 Edge. Both are crashing with the same error and both have the current Android Version with newest Google Play Services.

**Comment by adappter** [comment]
Found the issue!
com.google.android.gms:play-services-location and play-services-map should be updated to version 11

**Comment by adappter** [comment]
Also you have to update the Google SDK for iOS
