### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ZiFFeL1992** [mapsplugin/v2.0-demo#9]
```
Fetching plugin "https://github.com/mapsplugin/cordova-plugin-googlemaps.git" via git clone
Repository "https://github.com/mapsplugin/cordova-plugin-googlemaps.git" checked out to git ref "multiple_maps".
Installing "cordova-plugin-googlemaps" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-googlemaps':CordovaError: Uh oh!
"/Users/guille/Code/projects/app/platforms/android/src/plugin/google/maps/AsyncLicenseInfo.java" already exists!
    at copyNewFile (/Users/guille/Code/projects/app/platforms/android/cordova/lib/pluginHandlers.js:232:15)
    at install (/Users/guille/Code/projects/app/platforms/android/cordova/lib/pluginHandlers.js:37:17)
    at Object.process (/Users/guille/Code/projects/app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/guille/Code/projects/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/guille/Code/projects/app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/guille/Code/projects/app/platforms/android/cordova/Api.js:198:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!
"/Users/guille/Code/projects/app/platforms/android/src/plugin/google/maps/AsyncLicenseInfo.java" already exists!
```

This wasn't happening a couple of days ago, also I'm not facing this with branch master.

**Comment by wf9a5m75** [comment]
You didn't remove the plugin before install.

**Comment by wf9a5m75** [comment]
>"/Users/guille/Code/projects/app/platforms/android/src/plugin/google/maps/AsyncLicenseInfo.java" already exists!

This is everything.
